name: eShop build

on:
  push:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: main

    - name: Run unit tests
      run: dotnet test tests/Services/Coupon/*.Tests/*.csproj
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
    
    - name: Login to private registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: './src/Services/Coupon/Coupon.API/Dockerfile.acr'
        tags: 'linux-net6-coupon'
        push: true
